#!/usr/bin/env bash
# Inline _shared/http.ts into each function, producing one self-contained file
# per function for the Supabase dashboard's editor.
#
#   backend/supabase/functions/bundle.sh
#   -> functions/<name>/paste.ts
#
# For when the CLI is not an option. `supabase functions deploy` uses the real
# sources and ignores these; they exist only to be copied into the browser.
set -euo pipefail
cd "$(dirname "$0")"

shared=$(sed '1,/^ \*\//d' _shared/http.ts)   # drop the module's header comment

for fn in */; do
  name="${fn%/}"
  [ "$name" = "_shared" ] && continue
  [ -f "$name/index.ts" ] || continue

  {
    echo "// ============================================================================"
    echo "// $name — single file, for pasting into the Supabase dashboard."
    echo "//"
    echo "// Generated by functions/bundle.sh from $name/index.ts plus _shared/http.ts."
    echo "// Edit those, not this. Deploying with the CLI does not use this file."
    echo "// ============================================================================"
    echo
    # The shared helpers, in place of the import that pulled them in.
    echo "$shared"
    echo
    grep -v '^import { .* } from "\.\./_shared/http\.ts";$' "$name/index.ts"
  } > "$name/paste.ts"

  echo "wrote $name/paste.ts ($(wc -l < "$name/paste.ts") lines)"
done
