#!/usr/bin/env bash
# Inline _shared/*.ts (CORS, the branded email layout) into each function, producing one self-contained file
# per function for the Supabase dashboard's editor.
#
#   backend/supabase/functions/bundle.sh
#   -> functions/<name>/paste.ts
#
# For when the CLI is not an option. `supabase functions deploy` uses the real
# sources and ignores these; they exist only to be copied into the browser.
set -euo pipefail
cd "$(dirname "$0")"

# Each shared module, minus its header comment. Both go into every function:
# http.ts is CORS, email.ts the branded email layout.
shared=$(for m in _shared/http.ts _shared/email.ts; do sed '1,/^ \*\//d' "$m"; echo; done)

for fn in */; do
  name="${fn%/}"
  [ "$name" = "_shared" ] && continue
  [ -f "$name/index.ts" ] || continue

  {
    echo "// ============================================================================"
    echo "// $name — single file, for pasting into the Supabase dashboard."
    echo "//"
    echo "// Generated by functions/bundle.sh from $name/index.ts plus _shared/*.ts."
    echo "// Edit those, not this. Deploying with the CLI does not use this file."
    echo "// ============================================================================"
    echo
    # The shared helpers, in place of the import that pulled them in.
    echo "$shared"
    echo
    grep -vE '^import \{ .* \} from "\.\./_shared/[a-z]+\.ts";$' "$name/index.ts"
  } > "$name/paste.ts"

  echo "wrote $name/paste.ts ($(wc -l < "$name/paste.ts") lines)"
done
