// ============================================================================
// notify-booking — single file, for pasting into the Supabase dashboard.
//
// Generated by functions/bundle.sh from notify-booking/index.ts plus _shared/*.ts.
// Edit those, not this. Deploying with the CLI does not use this file.
// ============================================================================


// The live site is bizarri.com. send-email-code is called from the browser, so
// an origin missing here means the guest cannot get a code and cannot book;
// the github.io host stays for as long as the old URL still resolves.
const DEFAULT_ORIGINS = [
  "https://bizarri.com",
  "https://www.bizarri.com",
  "https://almailgroup.github.io",
  "http://localhost:5173",
  "http://localhost:4173",
];

/** Set ALLOWED_ORIGINS as a comma-separated list to override. */
export function allowedOrigins(): string[] {
  const raw = Deno.env.get("ALLOWED_ORIGINS");
  return raw
    ? raw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean)
    : DEFAULT_ORIGINS;
}

export function corsHeaders(origin: string | null): Record<string, string> {
  const allowed = allowedOrigins();
  // Echo the caller's origin only when it is on the list, never "*".
  const allow = origin && allowed.includes(origin) ? origin : allowed[0];
  return {
    "Access-Control-Allow-Origin": allow,
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    Vary: "Origin",
  };
}

export function json(body: unknown, status: number, origin: string | null): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders(origin), "Content-Type": "application/json" },
  });
}


export type EmailLang = "en" | "ar";

const SITE = "https://bizarri.com";
const BLACK = "#0a0a0a";
const SAND = "#f3f2ef";
const RULE = "#e6e4df";
const MUTED = "#8a8a8a";

export function escapeHtml(s: string): string {
  return String(s).replace(
    /[<>&"]/g,
    (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" })[c] as string,
  );
}

/** "96594040955" -> "+965 94040955", the site's one way of writing it. */
export function formatPhone(digits: string): string {
  const d = String(digits).replace(/\D/g, "");
  return d.startsWith("965") && d.length === 11 ? `+965 ${d.slice(3)}` : `+${d}`;
}

/**
 * "Thu 15 Oct 2026" / "الخميس، 15 أكتوبر 2026" from "2026-10-15", read in
 * UTC so no server time zone can move it a day. Latin digits in Arabic, as
 * on the site.
 */
export function formatEmailDate(iso: string, lang: EmailLang): string {
  const [y, m, d] = iso.split("-").map(Number);
  const at = new Date(Date.UTC(y, m - 1, d));
  return lang === "ar"
    ? at.toLocaleDateString("ar-EG-u-nu-latn", {
        weekday: "long",
        day: "numeric",
        month: "long",
        year: "numeric",
        timeZone: "UTC",
      })
    : at.toLocaleDateString("en-GB", {
        weekday: "short",
        day: "numeric",
        month: "short",
        year: "numeric",
        timeZone: "UTC",
      });
}

export interface EmailRow {
  label: string;
  /** Already escaped: a value may carry a <span dir="ltr">. */
  valueHtml: string;
}

export interface BrandedEmail {
  lang: EmailLang;
  title: string;
  /** "Dear Fatima," -- plain text. */
  greeting?: string;
  /** Plain text, one paragraph each. */
  paragraphs?: string[];
  /** The booking reference, or the code: shown large, left to right. */
  panel?: { label: string; value: string; large?: boolean };
  rows?: EmailRow[];
  total?: { label: string; value: string };
  button?: { href: string; label: string };
  /** Small print under the button. Already escaped; may hold a link. */
  noteHtml?: string;
  /** The front of the chalet under the logo. Off for short, practical mail. */
  photo?: boolean;
  signOff?: boolean;
  /** Digits. No number, no WhatsApp link anywhere -- never a dead one. */
  whatsapp?: string;
  /** Profile URL for the footer. */
  instagram?: string;
}

const COPY = {
  en: {
    dir: "ltr",
    align: "left",
    font: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    home: `${SITE}/en`,
    eyebrow: "Bizarri Chalet &middot; Al Khiran",
    signOff: "Warm regards,",
    team: "The Bizarri Chalet team",
    name: "Bizarri Chalet",
    address: "Al Khiran Al Bahri, Road 278, Phase 3, Kuwait",
    whatsapp: "WhatsApp",
    instagram: "Instagram",
    member: "A member of Almail Group",
    logoAlt: "Bizarri Chalet",
    photoAlt: "The front of Bizarri Chalet",
  },
  ar: {
    dir: "rtl",
    align: "right",
    font: "Tahoma, 'Geeza Pro', 'Segoe UI', Arial, sans-serif",
    home: `${SITE}/ar`,
    eyebrow: "شاليه بيزاري &middot; الخيران",
    signOff: "مع أطيب التحيات،",
    team: "فريق شاليه بيزاري",
    name: "شاليه بيزاري",
    address: "الخيران البحري، طريق 278، المرحلة الثالثة، الكويت",
    whatsapp: "واتساب",
    instagram: "إنستغرام",
    member: "عضو في مجموعة الميل",
    logoAlt: "شاليه بيزاري",
    photoAlt: "واجهة شاليه بيزاري",
  },
} as const;

export function brandedEmail(e: BrandedEmail): string {
  const c = COPY[e.lang];
  const ar = e.lang === "ar";
  const f = c.font;
  const al = c.align;
  const year = new Date().getUTCFullYear();
  const handle = (e.instagram ?? "").match(/instagram\.com\/([^/?#]+)/i)?.[1];

  const label = (text: string) =>
    `<p style="margin:0 0 6px; font-size:11px; ${ar ? "" : "letter-spacing:3px; text-transform:uppercase; "}color:${MUTED};">${escapeHtml(text)}</p>`;

  const rows = (e.rows ?? [])
    .map(
      (r) => `
              <tr>
                <td align="${al}" style="text-align:${al}; padding:12px 0; border-bottom:1px solid ${RULE}; color:${MUTED}; width:38%;">${escapeHtml(r.label)}</td>
                <td align="${al}" style="text-align:${al}; padding:12px 0; border-bottom:1px solid ${RULE}; font-weight:600;">${r.valueHtml}</td>
              </tr>`,
    )
    .join("");
  const total = e.total
    ? `
              <tr>
                <td align="${al}" style="text-align:${al}; padding:14px 0 0; color:${MUTED};">${escapeHtml(e.total.label)}</td>
                <td align="${al}" style="text-align:${al}; padding:14px 0 0; font-size:20px; font-weight:700; color:${BLACK};">${escapeHtml(e.total.value)}</td>
              </tr>`
    : "";

  const footerLinks = [
    e.whatsapp
      ? `<a href="https://wa.me/${escapeHtml(e.whatsapp)}" target="_blank" style="color:#ffffff; text-decoration:none;">${c.whatsapp}&nbsp;<span dir="ltr">${escapeHtml(formatPhone(e.whatsapp)).replace(" ", "&nbsp;")}</span></a>`
      : "",
    handle
      ? `<a href="${escapeHtml(e.instagram!)}" target="_blank" style="color:#ffffff; text-decoration:none;">${c.instagram}&nbsp;<span dir="ltr">@${escapeHtml(handle)}</span></a>`
      : "",
    `<a href="${c.home}" target="_blank" style="color:#ffffff; text-decoration:none;">bizarri.com</a>`,
  ]
    .filter(Boolean)
    .join("\n              &nbsp;&middot;&nbsp;\n              ");

  return `<!DOCTYPE html>
<html lang="${e.lang}" dir="${c.dir}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>${escapeHtml(e.title)}</title>
<style>
  @media only screen and (max-width: 620px) {
    .px { padding-left: 24px !important; padding-right: 24px !important; }
    .h1 { font-size: 26px !important; line-height: 32px !important; }
    .panel { font-size: 24px !important; }
    .btn a { display: block !important; text-align: center !important; }
  }
</style>
</head>
<body dir="${c.dir}" style="margin:0; padding:0; background-color:${SAND}; -webkit-text-size-adjust:100%;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${SAND}" style="background-color:${SAND};">
  <tr>
    <td align="center" style="padding:32px 12px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" dir="${c.dir}" style="width:100%; max-width:600px; background-color:#ffffff;">
        <tr>
          <td align="center" bgcolor="${BLACK}" style="background-color:${BLACK}; padding:36px 24px 32px;">
            <a href="${c.home}" target="_blank" style="text-decoration:none;"><img src="${SITE}/email/bizarri-logo-white.png" width="168" height="61" alt="${c.logoAlt}" style="display:block; width:168px; height:auto; border:0; outline:none; color:#ffffff; font-family:${f}; font-size:24px;"></a>
          </td>
        </tr>${
          e.photo
            ? `
        <tr>
          <td style="line-height:0; font-size:0;"><img src="${SITE}/email/front.jpg" width="600" alt="${c.photoAlt}" style="display:block; width:100%; max-width:600px; height:auto; border:0;"></td>
        </tr>`
            : ""
        }
        <tr>
          <td class="px" align="${al}" style="text-align:${al}; padding:44px 48px 0; font-family:${f}; color:#1a1a1a;">
            <p style="margin:0 0 14px; font-size:11px; ${ar ? "" : "letter-spacing:3px; text-transform:uppercase; "}color:${MUTED};">${c.eyebrow}</p>
            <h1 class="h1" style="margin:0 0 24px; font-size:30px; line-height:36px; font-weight:700; color:${BLACK};">${escapeHtml(e.title)}</h1>${
              e.greeting
                ? `
            <p style="margin:0 0 16px; font-size:16px; line-height:26px;">${escapeHtml(e.greeting)}</p>`
                : ""
            }${(e.paragraphs ?? [])
              .map(
                (p) => `
            <p style="margin:0 0 16px; font-size:16px; line-height:26px; color:#3a3a3a;">${escapeHtml(p)}</p>`,
              )
              .join("")}
          </td>
        </tr>${
          e.panel
            ? `
        <tr>
          <td class="px" style="padding:16px 48px 0;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${SAND}" style="background-color:${SAND}; ${ar ? "border-right" : "border-left"}:3px solid ${BLACK};">
              <tr>
                <td align="${al}" style="text-align:${al}; padding:20px 24px; font-family:${f};">
                  ${label(e.panel.label)}
                  <p class="panel" dir="ltr" align="${al}" style="margin:0; font-family:'SFMono-Regular', Menlo, Consolas, 'Courier New', monospace; font-size:${e.panel.large ? 36 : 28}px; letter-spacing:${e.panel.large ? 8 : 2}px; color:${BLACK};">${escapeHtml(e.panel.value)}</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>`
            : ""
        }${
          rows || total
            ? `
        <tr>
          <td class="px" style="padding:28px 48px 0;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="font-family:${f}; font-size:15px; line-height:22px; color:#1a1a1a;">${rows}${total}
            </table>
          </td>
        </tr>`
            : ""
        }${
          e.button || e.noteHtml
            ? `
        <tr>
          <td class="px" align="${al}" style="text-align:${al}; padding:${e.button ? 40 : 28}px 48px 0;">${
            e.button
              ? `
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" class="btn" style="width:auto;">
              <tr>
                <td bgcolor="${BLACK}" style="background-color:${BLACK};">
                  <a href="${escapeHtml(e.button.href)}" target="_blank" style="display:inline-block; padding:16px 34px; font-family:${f}; font-size:13px; ${ar ? "" : "letter-spacing:2px; text-transform:uppercase; "}color:#ffffff; text-decoration:none;">${escapeHtml(e.button.label)}</a>
                </td>
              </tr>
            </table>`
              : ""
          }${
            e.noteHtml
              ? `
            <p style="margin:18px 0 0; font-family:${f}; font-size:13px; line-height:20px; color:${MUTED};">${e.noteHtml}</p>`
              : ""
          }
          </td>
        </tr>`
            : ""
        }
        <tr>
          <td class="px" align="${al}" style="text-align:${al}; padding:${e.signOff ? "36px 48px 48px" : "0 48px 40px"}; font-family:${f}; font-size:15px; line-height:24px; color:#1a1a1a;">${
            e.signOff ? `${c.signOff}<br>\n            <strong>${c.team}</strong>` : "&nbsp;"
          }</td>
        </tr>
        <tr>
          <td class="px" align="${al}" bgcolor="${BLACK}" style="text-align:${al}; background-color:${BLACK}; padding:36px 48px; font-family:${f};">
            <p style="margin:0 0 12px; font-size:12px; ${ar ? "" : "letter-spacing:3px; text-transform:uppercase; "}color:#ffffff;">${c.name}</p>
            <p style="margin:0 0 16px; font-size:13px; line-height:21px; color:#a3a3a3;">${c.address}</p>
            <p style="margin:0 0 20px; font-size:13px; line-height:21px; color:#a3a3a3;">
              ${footerLinks}
            </p>
            <p style="margin:0; font-size:11px; line-height:18px; color:#6b6b6b;">${c.member} &middot; &copy; ${year} ${c.name}</p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>`;
}

/**
 * Every email the booking flow sends after the request exists.
 *
 * On INSERT: the team is told a request arrived, by email and by WhatsApp via
 * CallMeBot, and the guest gets their own copy with the reference.
 *
 * On UPDATE: if the status changed to accepted, rejected or cancelled, the
 * guest is told what was decided. Any other update — an edited phone number,
 * an internal note — sends nothing, or every keystroke in the admin panel
 * would be an email.
 *
 * Wired as Supabase Database Webhooks on public.bookings, so a notification is
 * a consequence of the row changing rather than something a browser has to
 * remember to do — closing the tab cannot lose it.
 *
 * Recipients for both channels come from public.settings — editable from the
 * admin panel's Site Settings tab — falling back to secrets if the relevant
 * row is empty or unreachable. SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are
 * provided automatically to every Edge Function; no extra secret is needed
 * to read settings.
 *
 * Email needs RESEND_API_KEY. WhatsApp needs each recipient to have already
 * opted in with CallMeBot (message their number, get an API key back) —
 * see backend/supabase/README.md for the exact steps. Either channel being
 * unconfigured just skips that channel; it never blocks the other, and a
 * booking having already succeeded is never put at risk by a notification
 * failing.
 */

interface WhatsAppRecipient {
  phone: string;
  apikey: string;
}

interface BookingRecord {
  ref: string;
  chalet_id: number;
  start_date: string;
  end_date: string;
  days: number;
  total: number;
  currency: string;
  guest_name: string;
  guest_phone: string;
  guest_email: string;
  guests: number;
  notes: string | null;
  status?: string | null;
  /** The language the guest booked in, for their copy of the email. */
  lang?: string | null;
  /** "admin" when it was entered from the dashboard rather than requested. */
  source?: string | null;
  /** False when the admin asked for the guest not to be emailed. */
  notify_guest?: boolean | null;
}

interface WebhookPayload {
  type?: string;
  record?: BookingRecord;
  old_record?: BookingRecord | null;
}

/**
 * The statuses worth telling a guest about.
 *
 * "pending" is in here for the move *back* — an admin who accepted and then
 * reconsidered leaves the guest holding a confirmation that is no longer
 * true, which is worse than never having been told. A new request is also
 * pending, but that arrives as an INSERT and is handled before this is read.
 */
const NOTIFIED_STATUSES = ["accepted", "rejected", "cancelled", "pending"];

/**
 * What one webhook delivery should cause.
 *
 * Pure and exported so it can be tested without a Deno runtime — the routing
 * is the part with the edge cases, and an UPDATE hook fires on every column,
 * not just the one that matters.
 */
export function classify(payload: WebhookPayload | null): {
  action: "new" | "admin" | "decision" | "ignore";
  reason?: string;
} {
  const record = payload?.record;
  if (!record?.ref)
    return { action: "ignore", reason: "no booking in payload" };

  // A booking the admin typed in is not a request for the team to act on --
  // they made it -- so it only ever concerns the guest, and only if the admin
  // left "email the guest" on. Checked before the generic insert below.
  if (payload?.type === "INSERT" && record.source === "admin") {
    if (record.notify_guest === false)
      return { action: "ignore", reason: "admin booking, guest not to be emailed" };
    if (record.status !== "accepted" && record.status !== "pending")
      return { action: "ignore", reason: `admin booking with status ${record.status}` };
    return { action: "admin" };
  }

  // A direct call (no webhook envelope) is treated as a new request, which is
  // how this function was invoked before there was anything else to do.
  if (payload?.type === "INSERT" || !payload?.type) return { action: "new" };

  if (payload.type === "UPDATE") {
    // Without the previous row there is no evidence anything changed, and
    // "probably a decision" is not good enough to mail a guest about.
    if (!payload.old_record)
      return { action: "ignore", reason: "no previous row" };
    const before = payload.old_record.status ?? null;
    const after = record.status ?? null;
    if (before === after)
      return { action: "ignore", reason: "status unchanged" };
    if (!after || !NOTIFIED_STATUSES.includes(after)) {
      return {
        action: "ignore",
        reason: `status ${after} is not worth an email`,
      };
    }
    return { action: "decision" };
  }

  return { action: "ignore", reason: `unhandled event ${payload.type}` };
}

/** One row from public.settings, or null on any failure — never throws, so a
 *  settings read failure falls through to the secret-based default instead
 *  of dropping the notification. */
async function readSetting(key: string): Promise<unknown> {
  const url = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !serviceKey) return null;
  try {
    const res = await fetch(
      `${url}/rest/v1/settings?key=eq.${key}&select=value`,
      {
        headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` },
      },
    );
    if (!res.ok) return null;
    const rows = (await res.json()) as { value: unknown }[];
    return rows[0]?.value ?? null;
  } catch {
    return null;
  }
}

/**
 * The public WhatsApp number, digits only, for the link in a guest's email.
 *
 * Guests are not sent WhatsApp messages — that needs a WhatsApp Business API
 * and Meta-approved templates, and the site deliberately does not use one —
 * but a guest starting the conversation needs no approval at all. So the
 * emails carry a tappable link rather than a number to copy out by hand.
 */
/** The Instagram profile in Site Settings, for the emails' footer. */
async function instagramUrl(): Promise<string> {
  const contact = await readSetting("contact");
  const raw =
    contact && typeof contact === "object"
      ? ((contact as Record<string, unknown>).instagram ?? "")
      : "";
  return String(raw) || DEFAULT_INSTAGRAM;
}

const DEFAULT_INSTAGRAM = "https://www.instagram.com/bizarri.chalet";

async function guestWhatsAppNumber(): Promise<string> {
  const contact = await readSetting("contact");
  const raw =
    contact && typeof contact === "object"
      ? ((contact as Record<string, unknown>).whatsapp ?? "")
      : "";
  const digits = String(raw).replace(/\D/g, "");
  return digits || (Deno.env.get("CONTACT_WHATSAPP") ?? "96594040955");
}

/** Editable from Site Settings, so an admin can change recipients without a
 *  redeploy. */
async function notifyEmailsFromSettings(): Promise<string[] | null> {
  const value = await readSetting("notify_emails");
  if (!Array.isArray(value)) return null;
  const emails = value.filter(
    (v): v is string => typeof v === "string" && v.length > 0,
  );
  return emails.length > 0 ? emails : null;
}

/** Same idea, for WhatsApp: each recipient needs their own CallMeBot API key
 *  (it's issued per phone number, not per account), so this is a list of
 *  {phone, apikey} pairs rather than a plain list of numbers. */
async function notifyWhatsAppFromSettings(): Promise<
  WhatsAppRecipient[] | null
> {
  const value = await readSetting("notify_whatsapp");
  if (!Array.isArray(value)) return null;
  const recipients = value.filter(
    (v): v is WhatsAppRecipient =>
      !!v &&
      typeof v === "object" &&
      typeof (v as WhatsAppRecipient).phone === "string" &&
      typeof (v as WhatsAppRecipient).apikey === "string" &&
      (v as WhatsAppRecipient).phone.length > 0 &&
      (v as WhatsAppRecipient).apikey.length > 0,
  );
  return recipients.length > 0 ? recipients : null;
}

/**
 * When to arrive and when to leave. The same rule the site shows (see
 * checkOutDay in frontend/src/lib/booking.ts): in at 2 PM on the first booked
 * day, out at noon the morning after the last -- so a single Monday is Monday
 * 2 PM to Tuesday 12 PM, and the Thu-Sat weekend ends Sunday at noon, two
 * hours before the weekday's guests arrive.
 */
const CHECK_IN_HOUR = 14;
const CHECK_OUT_HOUR = 12;

/** The morning after the last booked day. Dates stay strings, in UTC, so no
 *  timezone can move them: "2026-10-18" is the 18th wherever this runs. */
export function checkOutDate(end: string): string {
  const d = new Date(`${end}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

/** "2:00 PM" / "2:00 م": the site's own formatting, Latin digits in both. */
export function formatHour(hour: number, lang: "en" | "ar"): string {
  return new Date(Date.UTC(2000, 0, 1, hour)).toLocaleTimeString(
    lang === "ar" ? "ar-EG-u-nu-latn" : "en-US",
    { hour: "numeric", minute: "2-digit", timeZone: "UTC" },
  );
}

/** Check-in and check-out as two rows: a readable date and the hour. */
function stayRows(b: BookingRecord, lang: "en" | "ar"): EmailRow[] {
  const label =
    lang === "ar"
      ? { in: "الوصول", out: "المغادرة" }
      : { in: "Check-in", out: "Check-out" };
  const value = (date: string, hour: number) =>
    `${escapeHtml(formatEmailDate(date, lang))} &middot; ${escapeHtml(formatHour(hour, lang))}`;
  return [
    { label: label.in, valueHtml: value(b.start_date, CHECK_IN_HOUR) },
    { label: label.out, valueHtml: value(checkOutDate(b.end_date), CHECK_OUT_HOUR) },
  ];
}

function chaletName(b: BookingRecord, lang: "en" | "ar"): string {
  return lang === "ar" ? `شاليه بيزاري ${b.chalet_id}` : `Bizarri Chalet ${b.chalet_id}`;
}

/** "KD 350" / "350 د.ك", as the website writes a price. */
function money(b: BookingRecord, lang: "en" | "ar"): string {
  const n = Number(b.total).toLocaleString("en-US", { maximumFractionDigits: 3 });
  const kwd = (b.currency ?? "KWD").toUpperCase() === "KWD";
  if (lang === "ar") return kwd ? `${n} د.ك` : `${n} ${b.currency}`;
  return kwd ? `KD ${n}` : `${b.currency} ${n}`;
}

/** The stay as the guest sees it: chalet, in, out, guests. */
function guestRows(b: BookingRecord, lang: "en" | "ar"): EmailRow[] {
  const ar = lang === "ar";
  return [
    { label: ar ? "الشاليه" : "Chalet", valueHtml: escapeHtml(chaletName(b, lang)) },
    ...stayRows(b, lang),
    { label: ar ? "عدد الضيوف" : "Guests", valueHtml: escapeHtml(String(b.guests)) },
  ];
}

const REFERENCE = { en: "Booking reference", ar: "رقم الحجز" } as const;
const CHAT = { en: "Message us on WhatsApp", ar: "تواصل معنا عبر واتساب" } as const;

/** "Dear Fatima," / "مرحباً فاطمة،", or nothing if there is no name. */
function greeting(b: BookingRecord, lang: "en" | "ar"): string | undefined {
  const name = (b.guest_name ?? "").trim();
  if (!name) return undefined;
  return lang === "ar" ? `مرحباً ${name}،` : `Dear ${name},`;
}

/** The link to the lookup page, with the reminder to keep the reference. */
function lookupNote(lang: "en" | "ar", lead: string): string {
  const url = `https://bizarri.com/reservation/${lang}`;
  const link = `<a href="${url}" target="_blank" style="color:#0a0a0a; text-decoration:underline;">bizarri.com/reservation</a>`;
  return lang === "ar"
    ? `${escapeHtml(lead)} يمكنك الاستعلام عن حجزك في أي وقت عبر ${link} باستخدام رقم الحجز.`
    : `${escapeHtml(lead)} You can check your booking any time at ${link} with your reference.`;
}

/** The team's alert: everything needed to decide, and the way to decide it. */
export function render(b: BookingRecord): string {
  const rows: EmailRow[] = [
    { label: "Chalet", valueHtml: escapeHtml(chaletName(b, "en")) },
    ...stayRows(b, "en"),
    { label: "Days", valueHtml: escapeHtml(String(b.days)) },
    { label: "Guests", valueHtml: escapeHtml(String(b.guests)) },
    { label: "Guest", valueHtml: escapeHtml(b.guest_name) },
    { label: "Phone", valueHtml: `<span dir="ltr">${escapeHtml(b.guest_phone)}</span>` },
    { label: "Email", valueHtml: escapeHtml(b.guest_email) },
  ];
  if (b.notes) rows.push({ label: "Notes", valueHtml: escapeHtml(b.notes) });
  return brandedEmail({
    lang: "en",
    title: "New booking request",
    paragraphs: ["A new request has arrived. Accept or reject it in the admin dashboard."],
    panel: { label: REFERENCE.en, value: b.ref },
    rows,
    total: { label: "Total", value: money(b, "en") },
    button: { href: "https://bizarri.com/admin/en", label: "Open the dashboard" },
  });
}

/**
 * The guest's own copy. Deliberately a different message from the team's: it
 * leads with the reference, because that is the one thing they need to keep,
 * and it says the request is not yet confirmed so nobody turns up on the
 * strength of this email alone.
 */
export function renderGuest(
  b: BookingRecord,
  lang: "en" | "ar",
  whatsapp = "",
  instagram = DEFAULT_INSTAGRAM,
): string {
  const ar = lang === "ar";
  return brandedEmail({
    lang,
    title: ar ? "استلمنا طلب حجزك" : "We have your booking request",
    greeting: greeting(b, lang),
    paragraphs: [
      ar
        ? "طلبك قيد المراجعة. سنتواصل معك قريباً لتأكيد الحجز."
        : "Your request is being reviewed. We will contact you shortly to confirm.",
    ],
    panel: { label: REFERENCE[lang], value: b.ref },
    rows: guestRows(b, lang),
    total: { label: ar ? "الإجمالي" : "Total", value: money(b, lang) },
    button: whatsapp ? { href: `https://wa.me/${whatsapp}`, label: CHAT[lang] } : undefined,
    noteHtml: lookupNote(
      lang,
      ar ? "احتفظ برقم الحجز." : "Keep this reference.",
    ),
    photo: true,
    signOff: true,
    whatsapp,
    instagram,
  });
}

/**
 * What the guest is told once a decision is made.
 *
 * Four different messages, because "rejected" needs to read as an apology
 * with a way forward rather than as a status code. The internal admin note is
 * deliberately not included: the admin panel labels it internal and an admin
 * writing "haggled, gave discount" there does not expect the guest to read it.
 */
export function renderDecision(
  b: BookingRecord,
  lang: "en" | "ar",
  whatsapp = "",
  instagram = DEFAULT_INSTAGRAM,
): string {
  const ar = lang === "ar";
  const status = b.status ?? "";
  const copy: Record<string, { title: string; body: string }> = ar
    ? {
        accepted: {
          title: "تم تأكيد حجزك",
          body: "يسعدنا تأكيد إقامتك في شاليه بيزاري. نتطلع لاستقبالك.",
        },
        rejected: {
          title: "لم نتمكن من تأكيد حجزك",
          body: "نأسف، هذه التواريخ غير متاحة. تواصل معنا عبر واتساب وسنساعدك في إيجاد موعد آخر.",
        },
        cancelled: {
          title: "تم إلغاء حجزك",
          body: "تم إلغاء هذا الحجز. إذا لم تطلب ذلك، يرجى التواصل معنا.",
        },
        pending: {
          title: "حجزك قيد المراجعة",
          body: "أعدنا طلبك إلى قائمة الانتظار بينما نراجع التفاصيل. سنتواصل معك قريباً بالتأكيد النهائي.",
        },
      }
    : {
        accepted: {
          title: "Your booking is confirmed",
          body: "We are glad to confirm your stay at Bizarri Chalet. We look forward to welcoming you.",
        },
        rejected: {
          title: "We could not confirm your booking",
          body: "We are sorry — these dates are not available. Message us on WhatsApp and we will help you find another date.",
        },
        cancelled: {
          title: "Your booking has been cancelled",
          body: "This booking has been cancelled. If you did not ask for this, please get in touch.",
        },
        pending: {
          title: "Your booking is back under review",
          body: "We have put your request back on the waiting list while we check the details. We will be in touch shortly to confirm.",
        },
      };
  const t = copy[status] ?? copy.accepted;

  // The stay is shown while it might still happen. A refusal or a
  // cancellation does not need the price of something that is not.
  const live = status === "accepted" || status === "pending";

  return brandedEmail({
    lang,
    title: t.title,
    greeting: greeting(b, lang),
    paragraphs: [t.body],
    panel: { label: REFERENCE[lang], value: b.ref },
    rows: live ? guestRows(b, lang) : undefined,
    total: live ? { label: ar ? "الإجمالي" : "Total", value: money(b, lang) } : undefined,
    button: whatsapp ? { href: `https://wa.me/${whatsapp}`, label: CHAT[lang] } : undefined,
    noteHtml: live
      ? lookupNote(lang, ar ? "لأي استفسار، تواصل معنا." : "Any questions, just get in touch.")
      : escapeHtml(ar ? "لأي استفسار، تواصل معنا." : "Any questions, just get in touch."),
    photo: live,
    signOff: true,
    whatsapp,
    instagram,
  });
}

/** Plain-text with WhatsApp's own emphasis markup (*bold*), not HTML. */
export function renderWhatsApp(b: BookingRecord): string {
  const lines = [
    `*New booking request*`,
    `Ref: ${b.ref}`,
    `Chalet: Bizarri Chalet ${b.chalet_id}`,
    `Dates: ${b.start_date} → ${b.end_date} (${b.days} days)`,
    `Check-in: ${b.start_date} ${formatHour(CHECK_IN_HOUR, "en")}`,
    `Check-out: ${checkOutDate(b.end_date)} ${formatHour(CHECK_OUT_HOUR, "en")}`,
    `Total: ${b.currency} ${b.total}`,
    `Guest: ${b.guest_name}`,
    `Phone: ${b.guest_phone}`,
    `Email: ${b.guest_email}`,
    `Guests: ${b.guests}`,
  ];
  if (b.notes) lines.push(`Notes: ${b.notes}`);
  return lines.join("\n");
}

/**
 * Send one WhatsApp message via CallMeBot. CallMeBot only delivers to the
 * number that generated the apikey — there is no way to message an arbitrary
 * number with one shared key, which is why recipients are {phone, apikey}
 * pairs rather than a plain phone list.
 */
async function sendWhatsApp(
  recipient: WhatsAppRecipient,
  text: string,
): Promise<boolean> {
  try {
    const url =
      `https://api.callmebot.com/whatsapp.php` +
      `?phone=${encodeURIComponent(recipient.phone)}` +
      `&text=${encodeURIComponent(text)}` +
      `&apikey=${encodeURIComponent(recipient.apikey)}`;
    const res = await fetch(url);
    if (!res.ok) {
      console.error(
        "notify-booking: callmebot failed",
        recipient.phone,
        res.status,
        await res.text(),
      );
      return false;
    }
    return true;
  } catch (e) {
    console.error("notify-booking: callmebot error", recipient.phone, e);
    return false;
  }
}

interface DeliveryResult {
  attempted: boolean;
  delivered: boolean;
  reason?: string;
}

async function sendEmail(booking: BookingRecord): Promise<DeliveryResult> {
  const key = Deno.env.get("RESEND_API_KEY");
  if (!key) {
    console.log(
      "notify-booking: RESEND_API_KEY unset, skipping email",
      booking.ref,
    );
    return { attempted: false, delivered: false, reason: "no api key" };
  }

  const to =
    (await notifyEmailsFromSettings()) ??
    (Deno.env.get("NOTIFY_EMAILS") ?? "admin@almailgroup.com")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  const from =
    Deno.env.get("NOTIFY_FROM") ?? "Bizarri Chalet <onboarding@resend.dev>";

  // Caught here like the guest's and the decision emails: a network error
  // reaching Resend used to escape, reject the Promise.all in the handler,
  // and turn the whole delivery into a 500 -- taking the guest's copy down
  // with the team's, though the two are meant to be independent.
  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to,
        subject: `New booking ${booking.ref} — Chalet ${booking.chalet_id}`,
        html: render(booking),
        reply_to: booking.guest_email,
      }),
    });

    if (!res.ok) {
      console.error(
        "notify-booking: resend failed",
        res.status,
        await res.text(),
      );
      return { attempted: true, delivered: false };
    }
    return { attempted: true, delivered: true };
  } catch (e) {
    console.error("notify-booking: team email error", e);
    return { attempted: true, delivered: false };
  }
}

/**
 * The guest's copy. Failing to reach the guest must never look like the
 * booking failed \u2014 the row already exists by the time this runs \u2014 so this
 * reports its own outcome and never throws.
 */
async function sendGuestEmail(booking: BookingRecord): Promise<DeliveryResult> {
  const key = Deno.env.get("RESEND_API_KEY");
  if (!key) return { attempted: false, delivered: false, reason: "no api key" };
  if (!booking.guest_email)
    return { attempted: false, delivered: false, reason: "no address" };

  const lang: "en" | "ar" = booking.lang === "ar" ? "ar" : "en";
  const from =
    Deno.env.get("NOTIFY_FROM") ?? "Bizarri Chalet <onboarding@resend.dev>";
  const replyTo =
    (await notifyEmailsFromSettings())?.[0] ?? Deno.env.get("NOTIFY_EMAILS");
  const whatsapp = await guestWhatsAppNumber();

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [booking.guest_email],
        subject:
          lang === "ar"
            ? `\u0637\u0644\u0628 \u0627\u0644\u062d\u062c\u0632 ${booking.ref} \u2014 \u0634\u0627\u0644\u064a\u0647 \u0628\u064a\u0632\u0627\u0631\u064a`
            : `Your booking request ${booking.ref} \u2014 Bizarri Chalet`,
        html: renderGuest(booking, lang, whatsapp, await instagramUrl()),
        ...(replyTo ? { reply_to: replyTo } : {}),
      }),
    });
    if (!res.ok) {
      console.error(
        "notify-booking: guest email failed",
        res.status,
        await res.text(),
      );
      return { attempted: true, delivered: false };
    }
    return { attempted: true, delivered: true };
  } catch (e) {
    console.error("notify-booking: guest email error", e);
    return { attempted: true, delivered: false };
  }
}

/** The decision, to the guest. Never throws, for the same reason as above. */
async function sendDecisionEmail(
  booking: BookingRecord,
): Promise<DeliveryResult> {
  const key = Deno.env.get("RESEND_API_KEY");
  if (!key) return { attempted: false, delivered: false, reason: "no api key" };
  if (!booking.guest_email)
    return { attempted: false, delivered: false, reason: "no address" };

  const lang: "en" | "ar" = booking.lang === "ar" ? "ar" : "en";
  const from =
    Deno.env.get("NOTIFY_FROM") ?? "Bizarri Chalet <onboarding@resend.dev>";
  const replyTo =
    (await notifyEmailsFromSettings())?.[0] ?? Deno.env.get("NOTIFY_EMAILS");
  const confirmed = booking.status === "accepted";
  const whatsapp = await guestWhatsAppNumber();

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from,
        to: [booking.guest_email],
        subject:
          lang === "ar"
            ? `${confirmed ? "\u062a\u0645 \u062a\u0623\u0643\u064a\u062f \u062d\u062c\u0632\u0643" : "\u062a\u062d\u062f\u064a\u062b \u0639\u0644\u0649 \u062d\u062c\u0632\u0643"} ${booking.ref}`
            : `${confirmed ? "Confirmed" : "Update"}: booking ${booking.ref} \u2014 Bizarri Chalet`,
        html: renderDecision(booking, lang, whatsapp, await instagramUrl()),
        ...(replyTo ? { reply_to: replyTo } : {}),
      }),
    });
    if (!res.ok) {
      console.error(
        "notify-booking: decision email failed",
        res.status,
        await res.text(),
      );
      return { attempted: true, delivered: false };
    }
    return { attempted: true, delivered: true };
  } catch (e) {
    console.error("notify-booking: decision email error", e);
    return { attempted: true, delivered: false };
  }
}

async function sendAllWhatsApp(
  booking: BookingRecord,
): Promise<DeliveryResult> {
  const configured = await notifyWhatsAppFromSettings();
  const envPhone = Deno.env.get("CALLMEBOT_PHONE");
  const envKey = Deno.env.get("CALLMEBOT_APIKEY");
  const recipients =
    configured ??
    (envPhone && envKey ? [{ phone: envPhone, apikey: envKey }] : null);

  if (!recipients) {
    console.log(
      "notify-booking: no WhatsApp recipients configured, skipping",
      booking.ref,
    );
    return { attempted: false, delivered: false, reason: "no recipients" };
  }

  const text = renderWhatsApp(booking);
  const results = await Promise.all(
    recipients.map((r) => sendWhatsApp(r, text)),
  );
  return { attempted: true, delivered: results.some(Boolean) };
}

Deno.serve(async (req: Request) => {
  const origin = req.headers.get("origin");
  if (req.method === "OPTIONS")
    return new Response(null, { headers: corsHeaders(origin) });
  if (req.method !== "POST")
    return json({ error: "Method not allowed" }, 405, origin);

  try {
    const raw = await req.json().catch(() => null);
    // Database Webhooks post { type, table, record, old_record }; a direct
    // call may post the record itself.
    const payload: WebhookPayload | null = raw?.record
      ? (raw as WebhookPayload)
      : raw?.ref
        ? { record: raw as BookingRecord }
        : null;

    const { action, reason } = classify(payload);
    if (action === "ignore") {
      // 200, not an error: an update this function has nothing to say about is
      // a normal event, and a failing webhook would be retried forever.
      console.log("notify-booking: ignoring delivery -", reason);
      return json({ ok: true, action, reason }, 200, origin);
    }

    const booking = payload!.record!;

    if (action === "decision") {
      const guestEmail = await sendDecisionEmail(booking);
      return json({ ok: true, action, guestEmail }, 200, origin);
    }

    // Entered by the admin: an accepted booking gets the confirmation, a
    // pending one the same "we have your request" a guest would. The team is
    // not told about a booking one of them just made.
    if (action === "admin") {
      const guestEmail =
        booking.status === "accepted"
          ? await sendDecisionEmail(booking)
          : await sendGuestEmail(booking);
      return json({ ok: true, action, guestEmail }, 200, origin);
    }

    // The three sends are independent: one being unconfigured or failing
    // never stops the others from being attempted.
    const [email, guestEmail, whatsapp] = await Promise.all([
      sendEmail(booking),
      sendGuestEmail(booking),
      sendAllWhatsApp(booking),
    ]);

    return json({ ok: true, action, email, guestEmail, whatsapp }, 200, origin);
  } catch (e) {
    console.error("notify-booking error", e);
    return json({ error: "Unexpected error" }, 500, origin);
  }
});
