// ============================================================================
// notify-booking — single file, for pasting into the Supabase dashboard.
//
// Generated by functions/bundle.sh from notify-booking/index.ts plus _shared/http.ts.
// Edit those, not this. Deploying with the CLI does not use this file.
// ============================================================================


// The live site is bizarri.com. send-email-code is called from the browser, so
// an origin missing here means the guest cannot get a code and cannot book;
// the github.io host stays for as long as the old URL still resolves.
const DEFAULT_ORIGINS = [
  "https://bizarri.com",
  "https://www.bizarri.com",
  "https://almailgroup.github.io",
  "http://localhost:5173",
  "http://localhost:4173",
];

/** Set ALLOWED_ORIGINS as a comma-separated list to override. */
export function allowedOrigins(): string[] {
  const raw = Deno.env.get("ALLOWED_ORIGINS");
  return raw
    ? raw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean)
    : DEFAULT_ORIGINS;
}

export function corsHeaders(origin: string | null): Record<string, string> {
  const allowed = allowedOrigins();
  // Echo the caller's origin only when it is on the list, never "*".
  const allow = origin && allowed.includes(origin) ? origin : allowed[0];
  return {
    "Access-Control-Allow-Origin": allow,
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    Vary: "Origin",
  };
}

export function json(body: unknown, status: number, origin: string | null): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders(origin), "Content-Type": "application/json" },
  });
}

/**
 * Notifies the team when a booking request arrives — by email, and by
 * WhatsApp via CallMeBot.
 *
 * Wired as a Supabase Database Webhook on INSERT into public.bookings, so the
 * notification is a consequence of the row existing rather than something the
 * browser has to remember to do — a guest closing the tab cannot lose it.
 *
 * Recipients for both channels come from public.settings — editable from the
 * admin panel's Site Settings tab — falling back to secrets if the relevant
 * row is empty or unreachable. SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are
 * provided automatically to every Edge Function; no extra secret is needed
 * to read settings.
 *
 * Email needs RESEND_API_KEY. WhatsApp needs each recipient to have already
 * opted in with CallMeBot (message their number, get an API key back) —
 * see backend/supabase/README.md for the exact steps. Either channel being
 * unconfigured just skips that channel; it never blocks the other, and a
 * booking having already succeeded is never put at risk by a notification
 * failing.
 */

interface WhatsAppRecipient {
  phone: string;
  apikey: string;
}

interface BookingRecord {
  ref: string;
  chalet_id: number;
  start_date: string;
  end_date: string;
  days: number;
  total: number;
  currency: string;
  guest_name: string;
  guest_phone: string;
  guest_email: string;
  guests: number;
  notes: string | null;
  /** The language the guest booked in, for their copy of the email. */
  lang?: string | null;
}

/** One row from public.settings, or null on any failure — never throws, so a
 *  settings read failure falls through to the secret-based default instead
 *  of dropping the notification. */
async function readSetting(key: string): Promise<unknown> {
  const url = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !serviceKey) return null;
  try {
    const res = await fetch(`${url}/rest/v1/settings?key=eq.${key}&select=value`, {
      headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` },
    });
    if (!res.ok) return null;
    const rows = (await res.json()) as { value: unknown }[];
    return rows[0]?.value ?? null;
  } catch {
    return null;
  }
}

/** Editable from Site Settings, so an admin can change recipients without a
 *  redeploy. */
async function notifyEmailsFromSettings(): Promise<string[] | null> {
  const value = await readSetting("notify_emails");
  if (!Array.isArray(value)) return null;
  const emails = value.filter((v): v is string => typeof v === "string" && v.length > 0);
  return emails.length > 0 ? emails : null;
}

/** Same idea, for WhatsApp: each recipient needs their own CallMeBot API key
 *  (it's issued per phone number, not per account), so this is a list of
 *  {phone, apikey} pairs rather than a plain list of numbers. */
async function notifyWhatsAppFromSettings(): Promise<WhatsAppRecipient[] | null> {
  const value = await readSetting("notify_whatsapp");
  if (!Array.isArray(value)) return null;
  const recipients = value.filter(
    (v): v is WhatsAppRecipient =>
      !!v &&
      typeof v === "object" &&
      typeof (v as WhatsAppRecipient).phone === "string" &&
      typeof (v as WhatsAppRecipient).apikey === "string" &&
      (v as WhatsAppRecipient).phone.length > 0 &&
      (v as WhatsAppRecipient).apikey.length > 0,
  );
  return recipients.length > 0 ? recipients : null;
}

function esc(s: string): string {
  return s.replace(
    /[<>&"]/g,
    (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" })[c] as string,
  );
}

function render(b: BookingRecord): string {
  const row = (label: string, value: string) =>
    `<tr><td style="padding:6px 16px 6px 0;color:#666">${label}</td>` +
    `<td style="padding:6px 0;font-weight:500">${esc(value)}</td></tr>`;
  return `
    <div style="font-family:system-ui,sans-serif;max-width:520px">
      <p style="letter-spacing:.3em;text-transform:uppercase;font-size:11px;color:#888">
        Bizarri Chalet</p>
      <h2 style="font-weight:400;margin:4px 0 20px">New booking request</h2>
      <p style="font-family:monospace;font-size:18px;margin:0 0 20px">${esc(b.ref)}</p>
      <table style="border-collapse:collapse;font-size:14px">
        ${row("Chalet", `Bizarri Chalet ${b.chalet_id}`)}
        ${row("Dates", `${b.start_date} → ${b.end_date} (${b.days} days)`)}
        ${row("Total", `${b.currency} ${b.total}`)}
        ${row("Guest", b.guest_name)}
        ${row("Phone", b.guest_phone)}
        ${row("Email", b.guest_email)}
        ${row("Guests", String(b.guests))}
        ${b.notes ? row("Notes", b.notes) : ""}
      </table>
      <p style="margin-top:24px;font-size:13px;color:#888">
        Accept or reject this request in the admin dashboard.</p>
    </div>`;
}

/**
 * The guest's own copy. Deliberately a different message from the team's: it
 * leads with the reference, because that is the one thing they need to keep,
 * and it says the request is not yet confirmed so nobody turns up on the
 * strength of this email alone.
 */
function renderGuest(b: BookingRecord, lang: "en" | "ar"): string {
  const ar = lang === "ar";
  const t = ar
    ? {
        title: "استلمنا طلب حجزك",
        ref: "رقم الحجز",
        chalet: "الشاليه",
        dates: "التواريخ",
        total: "الإجمالي",
        guests: "عدد الضيوف",
        pending: "طلبك قيد المراجعة. سنتواصل معك قريباً لتأكيد الحجز.",
        keep: "احتفظ برقم الحجز للاستعلام عن حالته في أي وقت.",
      }
    : {
        title: "We have your booking request",
        ref: "Booking reference",
        chalet: "Chalet",
        dates: "Dates",
        total: "Total",
        guests: "Guests",
        pending: "Your request is being reviewed. We will contact you shortly to confirm.",
        keep: "Keep this reference to check the status of your booking at any time.",
      };
  const row = (label: string, value: string) =>
    `<tr><td style="padding:6px 16px 6px 0;color:#666">${esc(label)}</td>` +
    `<td style="padding:6px 0;font-weight:500">${esc(value)}</td></tr>`;
  return `
    <div style="font-family:system-ui,sans-serif;max-width:520px" ${ar ? 'dir="rtl"' : ""}>
      <p style="letter-spacing:.3em;text-transform:uppercase;font-size:11px;color:#888">
        Bizarri Chalet</p>
      <h2 style="font-weight:400;margin:4px 0 8px">${esc(t.title)}</h2>
      <p style="font-size:15px;color:#333;margin:0 0 20px">${esc(t.pending)}</p>
      <p style="text-transform:uppercase;letter-spacing:.2em;font-size:11px;color:#888;margin:0">
        ${esc(t.ref)}</p>
      <p style="font-family:monospace;font-size:26px;margin:4px 0 24px" dir="ltr">${esc(b.ref)}</p>
      <table style="border-collapse:collapse;font-size:14px">
        ${row(t.chalet, `Bizarri Chalet ${b.chalet_id}`)}
        ${row(t.dates, `${b.start_date} \u2192 ${b.end_date} (${b.days})`)}
        ${row(t.total, `${b.currency} ${b.total}`)}
        ${row(t.guests, String(b.guests))}
      </table>
      <p style="margin-top:24px;font-size:13px;color:#888">${esc(t.keep)}</p>
    </div>`;
}

/** Plain-text with WhatsApp's own emphasis markup (*bold*), not HTML. */
function renderWhatsApp(b: BookingRecord): string {
  const lines = [
    `*New booking request*`,
    `Ref: ${b.ref}`,
    `Chalet: Bizarri Chalet ${b.chalet_id}`,
    `Dates: ${b.start_date} → ${b.end_date} (${b.days} days)`,
    `Total: ${b.currency} ${b.total}`,
    `Guest: ${b.guest_name}`,
    `Phone: ${b.guest_phone}`,
    `Email: ${b.guest_email}`,
    `Guests: ${b.guests}`,
  ];
  if (b.notes) lines.push(`Notes: ${b.notes}`);
  return lines.join("\n");
}

/**
 * Send one WhatsApp message via CallMeBot. CallMeBot only delivers to the
 * number that generated the apikey — there is no way to message an arbitrary
 * number with one shared key, which is why recipients are {phone, apikey}
 * pairs rather than a plain phone list.
 */
async function sendWhatsApp(recipient: WhatsAppRecipient, text: string): Promise<boolean> {
  try {
    const url =
      `https://api.callmebot.com/whatsapp.php` +
      `?phone=${encodeURIComponent(recipient.phone)}` +
      `&text=${encodeURIComponent(text)}` +
      `&apikey=${encodeURIComponent(recipient.apikey)}`;
    const res = await fetch(url);
    if (!res.ok) {
      console.error("notify-booking: callmebot failed", recipient.phone, res.status, await res.text());
      return false;
    }
    return true;
  } catch (e) {
    console.error("notify-booking: callmebot error", recipient.phone, e);
    return false;
  }
}

interface DeliveryResult {
  attempted: boolean;
  delivered: boolean;
  reason?: string;
}

async function sendEmail(booking: BookingRecord): Promise<DeliveryResult> {
  const key = Deno.env.get("RESEND_API_KEY");
  if (!key) {
    console.log("notify-booking: RESEND_API_KEY unset, skipping email", booking.ref);
    return { attempted: false, delivered: false, reason: "no api key" };
  }

  const to =
    (await notifyEmailsFromSettings()) ??
    (Deno.env.get("NOTIFY_EMAILS") ?? "admin@almailgroup.com")
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  const from = Deno.env.get("NOTIFY_FROM") ?? "Bizarri Chalet <onboarding@resend.dev>";

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      from,
      to,
      subject: `New booking ${booking.ref} — Chalet ${booking.chalet_id}`,
      html: render(booking),
      reply_to: booking.guest_email,
    }),
  });

  if (!res.ok) {
    console.error("notify-booking: resend failed", res.status, await res.text());
    return { attempted: true, delivered: false };
  }
  return { attempted: true, delivered: true };
}

/**
 * The guest's copy. Failing to reach the guest must never look like the
 * booking failed \u2014 the row already exists by the time this runs \u2014 so this
 * reports its own outcome and never throws.
 */
async function sendGuestEmail(booking: BookingRecord): Promise<DeliveryResult> {
  const key = Deno.env.get("RESEND_API_KEY");
  if (!key) return { attempted: false, delivered: false, reason: "no api key" };
  if (!booking.guest_email) return { attempted: false, delivered: false, reason: "no address" };

  const lang: "en" | "ar" = booking.lang === "ar" ? "ar" : "en";
  const from = Deno.env.get("NOTIFY_FROM") ?? "Bizarri Chalet <onboarding@resend.dev>";
  const replyTo = (await notifyEmailsFromSettings())?.[0] ?? Deno.env.get("NOTIFY_EMAILS");

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from,
        to: [booking.guest_email],
        subject:
          lang === "ar"
            ? `\u0637\u0644\u0628 \u0627\u0644\u062d\u062c\u0632 ${booking.ref} \u2014 \u0634\u0627\u0644\u064a\u0647 \u0628\u064a\u0632\u0627\u0631\u064a`
            : `Your booking request ${booking.ref} \u2014 Bizarri Chalet`,
        html: renderGuest(booking, lang),
        ...(replyTo ? { reply_to: replyTo } : {}),
      }),
    });
    if (!res.ok) {
      console.error("notify-booking: guest email failed", res.status, await res.text());
      return { attempted: true, delivered: false };
    }
    return { attempted: true, delivered: true };
  } catch (e) {
    console.error("notify-booking: guest email error", e);
    return { attempted: true, delivered: false };
  }
}

async function sendAllWhatsApp(booking: BookingRecord): Promise<DeliveryResult> {
  const configured = await notifyWhatsAppFromSettings();
  const envPhone = Deno.env.get("CALLMEBOT_PHONE");
  const envKey = Deno.env.get("CALLMEBOT_APIKEY");
  const recipients = configured ?? (envPhone && envKey ? [{ phone: envPhone, apikey: envKey }] : null);

  if (!recipients) {
    console.log("notify-booking: no WhatsApp recipients configured, skipping", booking.ref);
    return { attempted: false, delivered: false, reason: "no recipients" };
  }

  const text = renderWhatsApp(booking);
  const results = await Promise.all(recipients.map((r) => sendWhatsApp(r, text)));
  return { attempted: true, delivered: results.some(Boolean) };
}

Deno.serve(async (req: Request) => {
  const origin = req.headers.get("origin");
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders(origin) });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405, origin);

  try {
    const payload = await req.json().catch(() => null);
    // Database Webhooks post { type, table, record, old_record }; a direct
    // call may post the record itself.
    const booking: BookingRecord | null =
      (payload?.record as BookingRecord) ?? (payload?.ref ? (payload as BookingRecord) : null);

    if (!booking?.ref) return json({ error: "No booking in payload" }, 400, origin);

    // The three sends are independent: one being unconfigured or failing
    // never stops the others from being attempted.
    const [email, guestEmail, whatsapp] = await Promise.all([
      sendEmail(booking),
      sendGuestEmail(booking),
      sendAllWhatsApp(booking),
    ]);

    return json({ ok: true, email, guestEmail, whatsapp }, 200, origin);
  } catch (e) {
    console.error("notify-booking error", e);
    return json({ error: "Unexpected error" }, 500, origin);
  }
});
