/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesLangRouteImport } from './routes/rules.$lang'
import { Route as ReservationLangRouteImport } from './routes/reservation.$lang'
import { Route as PrivacyLangRouteImport } from './routes/privacy.$lang'
import { Route as PhotosLangRouteImport } from './routes/photos.$lang'
import { Route as PackagesLangRouteImport } from './routes/packages.$lang'
import { Route as OffersLangRouteImport } from './routes/offers.$lang'
import { Route as NewsLangRouteImport } from './routes/news.$lang'
import { Route as FacilitiesLangRouteImport } from './routes/facilities.$lang'
import { Route as ContactLangRouteImport } from './routes/contact.$lang'
import { Route as BookingLangRouteImport } from './routes/booking.$lang'
import { Route as AdminLangRouteImport } from './routes/admin.$lang'
import { Route as AboutLangRouteImport } from './routes/about.$lang'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesLangRoute = RulesLangRouteImport.update({
  id: '/rules/$lang',
  path: '/rules/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationLangRoute = ReservationLangRouteImport.update({
  id: '/reservation/$lang',
  path: '/reservation/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyLangRoute = PrivacyLangRouteImport.update({
  id: '/privacy/$lang',
  path: '/privacy/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosLangRoute = PhotosLangRouteImport.update({
  id: '/photos/$lang',
  path: '/photos/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesLangRoute = PackagesLangRouteImport.update({
  id: '/packages/$lang',
  path: '/packages/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersLangRoute = OffersLangRouteImport.update({
  id: '/offers/$lang',
  path: '/offers/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsLangRoute = NewsLangRouteImport.update({
  id: '/news/$lang',
  path: '/news/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesLangRoute = FacilitiesLangRouteImport.update({
  id: '/facilities/$lang',
  path: '/facilities/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactLangRoute = ContactLangRouteImport.update({
  id: '/contact/$lang',
  path: '/contact/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingLangRoute = BookingLangRouteImport.update({
  id: '/booking/$lang',
  path: '/booking/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLangRoute = AdminLangRouteImport.update({
  id: '/admin/$lang',
  path: '/admin/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLangRoute = AboutLangRouteImport.update({
  id: '/about/$lang',
  path: '/about/$lang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang': typeof LangRoute
  '/about/$lang': typeof AboutLangRoute
  '/admin/$lang': typeof AdminLangRoute
  '/booking/$lang': typeof BookingLangRoute
  '/contact/$lang': typeof ContactLangRoute
  '/facilities/$lang': typeof FacilitiesLangRoute
  '/news/$lang': typeof NewsLangRoute
  '/offers/$lang': typeof OffersLangRoute
  '/packages/$lang': typeof PackagesLangRoute
  '/photos/$lang': typeof PhotosLangRoute
  '/privacy/$lang': typeof PrivacyLangRoute
  '/reservation/$lang': typeof ReservationLangRoute
  '/rules/$lang': typeof RulesLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang': typeof LangRoute
  '/about/$lang': typeof AboutLangRoute
  '/admin/$lang': typeof AdminLangRoute
  '/booking/$lang': typeof BookingLangRoute
  '/contact/$lang': typeof ContactLangRoute
  '/facilities/$lang': typeof FacilitiesLangRoute
  '/news/$lang': typeof NewsLangRoute
  '/offers/$lang': typeof OffersLangRoute
  '/packages/$lang': typeof PackagesLangRoute
  '/photos/$lang': typeof PhotosLangRoute
  '/privacy/$lang': typeof PrivacyLangRoute
  '/reservation/$lang': typeof ReservationLangRoute
  '/rules/$lang': typeof RulesLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang': typeof LangRoute
  '/about/$lang': typeof AboutLangRoute
  '/admin/$lang': typeof AdminLangRoute
  '/booking/$lang': typeof BookingLangRoute
  '/contact/$lang': typeof ContactLangRoute
  '/facilities/$lang': typeof FacilitiesLangRoute
  '/news/$lang': typeof NewsLangRoute
  '/offers/$lang': typeof OffersLangRoute
  '/packages/$lang': typeof PackagesLangRoute
  '/photos/$lang': typeof PhotosLangRoute
  '/privacy/$lang': typeof PrivacyLangRoute
  '/reservation/$lang': typeof ReservationLangRoute
  '/rules/$lang': typeof RulesLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$lang'
    | '/about/$lang'
    | '/admin/$lang'
    | '/booking/$lang'
    | '/contact/$lang'
    | '/facilities/$lang'
    | '/news/$lang'
    | '/offers/$lang'
    | '/packages/$lang'
    | '/photos/$lang'
    | '/privacy/$lang'
    | '/reservation/$lang'
    | '/rules/$lang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$lang'
    | '/about/$lang'
    | '/admin/$lang'
    | '/booking/$lang'
    | '/contact/$lang'
    | '/facilities/$lang'
    | '/news/$lang'
    | '/offers/$lang'
    | '/packages/$lang'
    | '/photos/$lang'
    | '/privacy/$lang'
    | '/reservation/$lang'
    | '/rules/$lang'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$lang'
    | '/about/$lang'
    | '/admin/$lang'
    | '/booking/$lang'
    | '/contact/$lang'
    | '/facilities/$lang'
    | '/news/$lang'
    | '/offers/$lang'
    | '/packages/$lang'
    | '/photos/$lang'
    | '/privacy/$lang'
    | '/reservation/$lang'
    | '/rules/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LangRoute: typeof LangRoute
  AboutLangRoute: typeof AboutLangRoute
  AdminLangRoute: typeof AdminLangRoute
  BookingLangRoute: typeof BookingLangRoute
  ContactLangRoute: typeof ContactLangRoute
  FacilitiesLangRoute: typeof FacilitiesLangRoute
  NewsLangRoute: typeof NewsLangRoute
  OffersLangRoute: typeof OffersLangRoute
  PackagesLangRoute: typeof PackagesLangRoute
  PhotosLangRoute: typeof PhotosLangRoute
  PrivacyLangRoute: typeof PrivacyLangRoute
  ReservationLangRoute: typeof ReservationLangRoute
  RulesLangRoute: typeof RulesLangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$lang': {
      id: '/rules/$lang'
      path: '/rules/$lang'
      fullPath: '/rules/$lang'
      preLoaderRoute: typeof RulesLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$lang': {
      id: '/reservation/$lang'
      path: '/reservation/$lang'
      fullPath: '/reservation/$lang'
      preLoaderRoute: typeof ReservationLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/$lang': {
      id: '/privacy/$lang'
      path: '/privacy/$lang'
      fullPath: '/privacy/$lang'
      preLoaderRoute: typeof PrivacyLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$lang': {
      id: '/photos/$lang'
      path: '/photos/$lang'
      fullPath: '/photos/$lang'
      preLoaderRoute: typeof PhotosLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$lang': {
      id: '/packages/$lang'
      path: '/packages/$lang'
      fullPath: '/packages/$lang'
      preLoaderRoute: typeof PackagesLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$lang': {
      id: '/offers/$lang'
      path: '/offers/$lang'
      fullPath: '/offers/$lang'
      preLoaderRoute: typeof OffersLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$lang': {
      id: '/news/$lang'
      path: '/news/$lang'
      fullPath: '/news/$lang'
      preLoaderRoute: typeof NewsLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/$lang': {
      id: '/facilities/$lang'
      path: '/facilities/$lang'
      fullPath: '/facilities/$lang'
      preLoaderRoute: typeof FacilitiesLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/$lang': {
      id: '/contact/$lang'
      path: '/contact/$lang'
      fullPath: '/contact/$lang'
      preLoaderRoute: typeof ContactLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$lang': {
      id: '/booking/$lang'
      path: '/booking/$lang'
      fullPath: '/booking/$lang'
      preLoaderRoute: typeof BookingLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$lang': {
      id: '/admin/$lang'
      path: '/admin/$lang'
      fullPath: '/admin/$lang'
      preLoaderRoute: typeof AdminLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$lang': {
      id: '/about/$lang'
      path: '/about/$lang'
      fullPath: '/about/$lang'
      preLoaderRoute: typeof AboutLangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LangRoute: LangRoute,
  AboutLangRoute: AboutLangRoute,
  AdminLangRoute: AdminLangRoute,
  BookingLangRoute: BookingLangRoute,
  ContactLangRoute: ContactLangRoute,
  FacilitiesLangRoute: FacilitiesLangRoute,
  NewsLangRoute: NewsLangRoute,
  OffersLangRoute: OffersLangRoute,
  PackagesLangRoute: PackagesLangRoute,
  PhotosLangRoute: PhotosLangRoute,
  PrivacyLangRoute: PrivacyLangRoute,
  ReservationLangRoute: ReservationLangRoute,
  RulesLangRoute: RulesLangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
