/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangRulesRouteImport } from './routes/$lang/rules'
import { Route as LangReservationRouteImport } from './routes/$lang/reservation'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangPhotosRouteImport } from './routes/$lang/photos'
import { Route as LangOffersRouteImport } from './routes/$lang/offers'
import { Route as LangNewsRouteImport } from './routes/$lang/news'
import { Route as LangFacilitiesRouteImport } from './routes/$lang/facilities'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangBookingRouteImport } from './routes/$lang/booking'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangSplatRouteImport } from './routes/$lang/$'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangRulesRoute = LangRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangReservationRoute = LangReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPhotosRoute = LangPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangOffersRoute = LangOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangNewsRoute = LangNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangFacilitiesRoute = LangFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookingRoute = LangBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/$': typeof LangSplatRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/booking': typeof LangBookingRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/facilities': typeof LangFacilitiesRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/photos': typeof LangPhotosRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/reservation': typeof LangReservationRoute
  '/$lang/rules': typeof LangRulesRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/booking': typeof LangBookingRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/facilities': typeof LangFacilitiesRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/photos': typeof LangPhotosRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/reservation': typeof LangReservationRoute
  '/$lang/rules': typeof LangRulesRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/$': typeof LangSplatRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/booking': typeof LangBookingRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/facilities': typeof LangFacilitiesRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/photos': typeof LangPhotosRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/reservation': typeof LangReservationRoute
  '/$lang/rules': typeof LangRulesRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/$'
    | '/$lang/about'
    | '/$lang/admin'
    | '/$lang/booking'
    | '/$lang/contact'
    | '/$lang/facilities'
    | '/$lang/news'
    | '/$lang/offers'
    | '/$lang/photos'
    | '/$lang/privacy'
    | '/$lang/reservation'
    | '/$lang/rules'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/$'
    | '/$lang/about'
    | '/$lang/admin'
    | '/$lang/booking'
    | '/$lang/contact'
    | '/$lang/facilities'
    | '/$lang/news'
    | '/$lang/offers'
    | '/$lang/photos'
    | '/$lang/privacy'
    | '/$lang/reservation'
    | '/$lang/rules'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/$'
    | '/$lang/about'
    | '/$lang/admin'
    | '/$lang/booking'
    | '/$lang/contact'
    | '/$lang/facilities'
    | '/$lang/news'
    | '/$lang/offers'
    | '/$lang/photos'
    | '/$lang/privacy'
    | '/$lang/reservation'
    | '/$lang/rules'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/rules': {
      id: '/$lang/rules'
      path: '/rules'
      fullPath: '/$lang/rules'
      preLoaderRoute: typeof LangRulesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/reservation': {
      id: '/$lang/reservation'
      path: '/reservation'
      fullPath: '/$lang/reservation'
      preLoaderRoute: typeof LangReservationRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/photos': {
      id: '/$lang/photos'
      path: '/photos'
      fullPath: '/$lang/photos'
      preLoaderRoute: typeof LangPhotosRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/offers': {
      id: '/$lang/offers'
      path: '/offers'
      fullPath: '/$lang/offers'
      preLoaderRoute: typeof LangOffersRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/news': {
      id: '/$lang/news'
      path: '/news'
      fullPath: '/$lang/news'
      preLoaderRoute: typeof LangNewsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/facilities': {
      id: '/$lang/facilities'
      path: '/facilities'
      fullPath: '/$lang/facilities'
      preLoaderRoute: typeof LangFacilitiesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/booking': {
      id: '/$lang/booking'
      path: '/booking'
      fullPath: '/$lang/booking'
      preLoaderRoute: typeof LangBookingRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangSplatRoute: typeof LangSplatRoute
  LangAboutRoute: typeof LangAboutRoute
  LangAdminRoute: typeof LangAdminRoute
  LangBookingRoute: typeof LangBookingRoute
  LangContactRoute: typeof LangContactRoute
  LangFacilitiesRoute: typeof LangFacilitiesRoute
  LangNewsRoute: typeof LangNewsRoute
  LangOffersRoute: typeof LangOffersRoute
  LangPhotosRoute: typeof LangPhotosRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangReservationRoute: typeof LangReservationRoute
  LangRulesRoute: typeof LangRulesRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangSplatRoute: LangSplatRoute,
  LangAboutRoute: LangAboutRoute,
  LangAdminRoute: LangAdminRoute,
  LangBookingRoute: LangBookingRoute,
  LangContactRoute: LangContactRoute,
  LangFacilitiesRoute: LangFacilitiesRoute,
  LangNewsRoute: LangNewsRoute,
  LangOffersRoute: LangOffersRoute,
  LangPhotosRoute: LangPhotosRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangReservationRoute: LangReservationRoute,
  LangRulesRoute: LangRulesRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
